export enum StarField {
    Seed,
    Index,
    Name,
    PositionX,
    PositionY,
    PositionZ,
    Mass,
    Age,
    Temperature,
    Type,
    Spectr,
    Luminosity,
    Radius,
    DysonRadius,
    DistanceFromBirth,
    DistanceFromNearestX,
    DistanceFromFurthestX,
    InitialHiveCount,
    MaxHiveCount,
}

export const starFieldsOrder = [
    StarField.Seed,
    StarField.Index,
    StarField.Name,
    StarField.Type,
    StarField.Spectr,
    StarField.Luminosity,
    StarField.PositionX,
    StarField.PositionY,
    StarField.PositionZ,
    StarField.DistanceFromBirth,
    StarField.DistanceFromNearestX,
    StarField.DistanceFromFurthestX,
    StarField.Radius,
    StarField.DysonRadius,
    StarField.Mass,
    StarField.Age,
    StarField.Temperature,
    StarField.InitialHiveCount,
    StarField.MaxHiveCount,
]

export enum PlanetField {
    Seed,
    Index,
    Name,
    Theme,
    Orbiting,
    TidallyLocked,
    OrbitRadius,
    OrbitInclination,
    OrbitLongitude,
    OrbitalPeriod,
    Obliquity,
    RotationPeriod,
    Wind,
    Luminosity,
}

export const planetFieldsOrder = [
    PlanetField.Seed,
    PlanetField.Index,
    PlanetField.Name,
    PlanetField.Theme,
    PlanetField.Orbiting,
    PlanetField.TidallyLocked,
    PlanetField.Wind,
    PlanetField.Luminosity,
    PlanetField.OrbitRadius,
    PlanetField.OrbitInclination,
    PlanetField.OrbitLongitude,
    PlanetField.OrbitalPeriod,
    PlanetField.Obliquity,
    PlanetField.RotationPeriod,
]
