use super::enums::{PlanetType, ThemeDistribute, VeinType};
use once_cell::sync::Lazy;
use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ThemeProto {
    pub id: i32,
    pub name: &'static str,
    #[serde(skip_serializing)]
    pub distribute: ThemeDistribute,
    #[serde(skip_serializing)]
    pub temperature: f32,
    #[serde(skip_serializing)]
    pub planet_type: PlanetType,
    #[serde(skip_serializing)]
    pub vein_spot: Vec<i32>,
    #[serde(skip_serializing)]
    pub vein_count: Vec<f32>,
    #[serde(skip_serializing)]
    pub vein_opacity: Vec<f32>,
    #[serde(skip_serializing)]
    pub rare_veins: Vec<VeinType>,
    #[serde(skip_serializing)]
    pub rare_settings: Vec<f32>,
    #[serde(skip_serializing)]
    pub gas_items: Vec<i32>,
    #[serde(skip_serializing)]
    pub gas_speeds: Vec<f32>,
}

pub const DEFAULT_THEME_PROTO: &'static ThemeProto = &ThemeProto {
    id: 0,
    name: "",
    distribute: ThemeDistribute::Default,
    temperature: 0.0,
    planet_type: PlanetType::None,
    vein_spot: vec![],
    vein_count: vec![],
    vein_opacity: vec![],
    rare_veins: vec![],
    rare_settings: vec![],
    gas_items: vec![],
    gas_speeds: vec![],
};

impl Default for ThemeProto {
    fn default() -> Self {
        DEFAULT_THEME_PROTO.clone()
    }
}

pub static THEME_PROTOS: Lazy<Vec<ThemeProto>> = Lazy::new(|| {
    vec![
        ThemeProto {
            id: 1,
            name: "Ocean 1",
            distribute: ThemeDistribute::Birth,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![7, 5, 0, 0, 8, 11, 18],
            vein_count: vec![0.7, 0.6, 0.0, 0.0, 1.0, 1.0, 1.0],
            vein_opacity: vec![0.6, 0.5, 0.0, 0.0, 0.7, 1.0, 1.0],
            rare_veins: vec![VeinType::Crysrub],
            rare_settings: vec![0.0, 1.0, 0.3, 0.3],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 2,
            name: "Gas 1",
            distribute: ThemeDistribute::Default,
            temperature: 2.0,
            planet_type: PlanetType::Gas,
            vein_spot: vec![],
            vein_count: vec![],
            vein_opacity: vec![],
            rare_veins: vec![],
            rare_settings: vec![],
            gas_items: vec![1120, 1121],
            gas_speeds: vec![0.96, 0.04],
        },
        ThemeProto {
            id: 3,
            name: "Gas 2",
            distribute: ThemeDistribute::Default,
            temperature: 1.0,
            planet_type: PlanetType::Gas,
            vein_spot: vec![],
            vein_count: vec![],
            vein_opacity: vec![],
            rare_veins: vec![],
            rare_settings: vec![],
            gas_items: vec![1120, 1121],
            gas_speeds: vec![0.96, 0.04],
        },
        ThemeProto {
            id: 4,
            name: "Gas 3",
            distribute: ThemeDistribute::Default,
            temperature: -1.0,
            planet_type: PlanetType::Gas,
            vein_spot: vec![],
            vein_count: vec![],
            vein_opacity: vec![],
            rare_veins: vec![],
            rare_settings: vec![],
            gas_items: vec![1011, 1120],
            gas_speeds: vec![0.7, 0.3],
        },
        ThemeProto {
            id: 5,
            name: "Gas 4",
            distribute: ThemeDistribute::Default,
            temperature: -2.0,
            planet_type: PlanetType::Gas,
            vein_spot: vec![],
            vein_count: vec![],
            vein_opacity: vec![],
            rare_veins: vec![],
            rare_settings: vec![],
            gas_items: vec![1011, 1120],
            gas_speeds: vec![0.7, 0.3],
        },
        ThemeProto {
            id: 6,
            name: "Desert 1",
            distribute: ThemeDistribute::Default,
            temperature: 2.0,
            planet_type: PlanetType::Desert,
            vein_spot: vec![3, 10, 0, 6, 10, 1, 0],
            vein_count: vec![0.5, 1.0, 0.0, 1.0, 1.0, 0.3, 0.0],
            vein_opacity: vec![0.6, 0.6, 0.0, 1.0, 1.0, 0.3, 0.0],
            rare_veins: vec![VeinType::Diamond],
            rare_settings: vec![0.0, 0.18, 0.2, 0.3],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 7,
            name: "Desert 2",
            distribute: ThemeDistribute::Default,
            temperature: -1.0,
            planet_type: PlanetType::Desert,
            vein_spot: vec![7, 2, 7, 3, 8, 1, 0],
            vein_count: vec![1.0, 0.5, 1.0, 1.0, 0.7, 0.3, 0.0],
            vein_opacity: vec![0.6, 0.6, 1.0, 1.0, 0.5, 0.3, 0.0],
            rare_veins: vec![VeinType::Fireice, VeinType::Fractal],
            rare_settings: vec![0.3, 0.5, 0.7, 0.5, 0.0, 0.3, 0.2, 0.6],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 8,
            name: "Ocean 2",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![7, 2, 12, 0, 4, 10, 22],
            vein_count: vec![0.6, 0.3, 0.9, 0.0, 0.8, 1.0, 1.0],
            vein_opacity: vec![0.6, 0.6, 0.6, 0.0, 0.5, 1.0, 1.0],
            rare_veins: vec![VeinType::Crysrub, VeinType::Bamboo],
            rare_settings: vec![0.0, 1.0, 0.3, 1.0, 0.0, 0.5, 0.2, 1.0],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 9,
            name: "Lava 1",
            distribute: ThemeDistribute::Default,
            temperature: 5.0,
            planet_type: PlanetType::Vocano,
            vein_spot: vec![15, 15, 2, 9, 4, 2, 0],
            vein_count: vec![1.0, 1.0, 0.6, 1.0, 0.6, 0.3, 0.0],
            vein_opacity: vec![1.0, 1.0, 0.6, 1.0, 0.5, 0.3, 0.0],
            rare_veins: vec![VeinType::Diamond, VeinType::Fractal, VeinType::Grat],
            rare_settings: vec![0.0, 0.2, 0.6, 0.7, 0.0, 0.2, 0.6, 0.7, 0.0, 0.1, 0.2, 0.8],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 10,
            name: "Ice 1",
            distribute: ThemeDistribute::Default,
            temperature: -5.0,
            planet_type: PlanetType::Ice,
            vein_spot: vec![5, 1, 3, 10, 2, 1, 0],
            vein_count: vec![0.6, 0.2, 0.8, 1.0, 0.8, 0.2, 0.0],
            vein_opacity: vec![1.0, 0.5, 1.0, 1.0, 1.0, 0.3, 0.0],
            rare_veins: vec![VeinType::Fireice, VeinType::Fractal, VeinType::Grat],
            rare_settings: vec![0.3, 1.0, 0.8, 1.0, 0.0, 0.2, 0.6, 0.4, 0.0, 0.1, 0.2, 0.4],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 11,
            name: "Desert 3",
            distribute: ThemeDistribute::Default,
            temperature: -2.0,
            planet_type: PlanetType::Desert,
            vein_spot: vec![3, 3, 3, 6, 12, 0, 0],
            vein_count: vec![0.5, 0.5, 0.5, 1.0, 1.2, 0.0, 0.0],
            vein_opacity: vec![0.6, 0.6, 0.9, 0.9, 1.5, 0.0, 0.0],
            rare_veins: vec![VeinType::Fireice, VeinType::Diamond, VeinType::Grat],
            rare_settings: vec![0.25, 0.5, 0.6, 0.6, 0.0, 0.2, 0.6, 0.7, 0.0, 0.1, 0.2, 0.5],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 12,
            name: "Desert 4",
            distribute: ThemeDistribute::Default,
            temperature: 1.0,
            planet_type: PlanetType::Desert,
            vein_spot: vec![2, 7, 8, 0, 7, 3, 0],
            vein_count: vec![0.4, 1.0, 1.0, 0.0, 1.0, 0.7, 0.0],
            vein_opacity: vec![0.8, 1.0, 1.0, 0.0, 1.0, 0.7, 0.0],
            rare_veins: vec![VeinType::Diamond, VeinType::Fractal, VeinType::Grat],
            rare_settings: vec![0.0, 0.25, 0.6, 0.6, 0.0, 0.25, 0.6, 0.6, 0.0, 0.1, 0.2, 0.5],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 13,
            name: "Volcanic 1",
            distribute: ThemeDistribute::Interstellar,
            temperature: 4.0,
            planet_type: PlanetType::Vocano,
            vein_spot: vec![10, 10, 2, 7, 4, 1, 0],
            vein_count: vec![1.0, 1.0, 0.6, 1.0, 0.6, 0.3, 0.0],
            vein_opacity: vec![1.0, 1.0, 0.6, 1.0, 0.5, 0.3, 0.0],
            rare_veins: vec![],
            rare_settings: vec![],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 14,
            name: "Ocean 3",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![4, 6, 0, 0, 10, 8, 12],
            vein_count: vec![0.7, 0.7, 0.0, 0.0, 1.0, 1.0, 1.0],
            vein_opacity: vec![0.5, 0.6, 0.0, 0.0, 0.8, 1.0, 1.0],
            rare_veins: vec![VeinType::Diamond, VeinType::Crysrub, VeinType::Bamboo],
            rare_settings: vec![0.0, 0.4, 0.3, 0.5, 0.0, 1.0, 0.3, 0.8, 0.0, 0.5, 0.2, 0.8],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 15,
            name: "Ocean 4",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![7, 4, 7, 1, 2, 7, 18],
            vein_count: vec![0.7, 0.6, 0.7, 0.4, 0.5, 1.0, 1.0],
            vein_opacity: vec![0.6, 0.5, 0.6, 0.5, 0.7, 1.0, 1.2],
            rare_veins: vec![VeinType::Crysrub, VeinType::Bamboo],
            rare_settings: vec![0.0, 1.0, 0.3, 1.0, 0.0, 0.5, 0.2, 1.0],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 16,
            name: "Ocean 5",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![0, 0, 0, 0, 0, 2, 10],
            vein_count: vec![0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 5.0],
            vein_opacity: vec![0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 2.0],
            rare_veins: vec![VeinType::Bamboo],
            rare_settings: vec![1.0, 1.0, 1.0, 0.9],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 17,
            name: "Desert 5",
            distribute: ThemeDistribute::Default,
            temperature: 1.0,
            planet_type: PlanetType::Desert,
            vein_spot: vec![2, 8, 9, 1, 3, 1, 0],
            vein_count: vec![1.0, 0.8, 0.8, 1.0, 0.7, 0.3, 0.0],
            vein_opacity: vec![0.6, 0.6, 1.0, 1.0, 0.5, 0.3, 0.0],
            rare_veins: vec![VeinType::Diamond, VeinType::Grat],
            rare_settings: vec![0.0, 0.7, 0.7, 0.5, 0.0, 0.1, 0.2, 0.7],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 18,
            name: "Ocean 6",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![5, 6, 8, 0, 4, 8, 22],
            vein_count: vec![0.6, 0.5, 0.8, 0.0, 0.8, 1.0, 1.0],
            vein_opacity: vec![0.6, 0.6, 0.6, 0.0, 0.5, 1.0, 1.0],
            rare_veins: vec![VeinType::Crysrub, VeinType::Bamboo],
            rare_settings: vec![0.0, 1.0, 0.3, 1.0, 0.0, 0.5, 0.2, 1.0],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 19,
            name: "Desert 6",
            distribute: ThemeDistribute::Interstellar,
            temperature: 1.0,
            planet_type: PlanetType::Desert,
            vein_spot: vec![2, 8, 2, 7, 4, 1, 0],
            vein_count: vec![1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.0],
            vein_opacity: vec![0.6, 0.8, 1.0, 0.8, 0.6, 0.3, 0.0],
            rare_veins: vec![VeinType::Diamond, VeinType::Fractal, VeinType::Grat],
            rare_settings: vec![0.0, 0.25, 0.6, 0.6, 0.0, 0.25, 0.6, 0.6, 0.0, 0.4, 0.3, 0.9],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 20,
            name: "Desert 7",
            distribute: ThemeDistribute::Default,
            temperature: -2.0,
            planet_type: PlanetType::Desert,
            vein_spot: vec![5, 11, 1, 8, 3, 1, 0],
            vein_count: vec![0.8, 1.0, 0.5, 1.0, 0.7, 0.3, 0.0],
            vein_opacity: vec![1.0, 1.0, 1.0, 1.0, 0.5, 0.3, 0.0],
            rare_veins: vec![VeinType::Fireice, VeinType::Diamond, VeinType::Grat],
            rare_settings: vec![0.25, 1.0, 0.6, 0.7, 0.0, 0.2, 0.6, 0.9, 0.0, 0.3, 0.4, 1.0],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 21,
            name: "Gas 5",
            distribute: ThemeDistribute::Interstellar,
            temperature: 1.0,
            planet_type: PlanetType::Gas,
            vein_spot: vec![],
            vein_count: vec![],
            vein_opacity: vec![],
            rare_veins: vec![],
            rare_settings: vec![],
            gas_items: vec![1120, 1121],
            gas_speeds: vec![0.84, 0.16],
        },
        ThemeProto {
            id: 22,
            name: "Desert 8",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![7, 4, 7, 2, 3, 6, 14],
            vein_count: vec![0.7, 0.6, 1.0, 0.8, 0.7, 1.0, 1.0],
            vein_opacity: vec![0.7, 0.6, 0.8, 0.7, 1.0, 1.2, 1.0],
            rare_veins: vec![VeinType::Crysrub, VeinType::Bamboo],
            rare_settings: vec![0.0, 1.0, 0.5, 1.0, 0.0, 0.6, 0.25, 1.0],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 23,
            name: "Desert 9",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.08,
            planet_type: PlanetType::Desert,
            vein_spot: vec![13, 2, 0, 2, 0, 2, 0],
            vein_count: vec![1.0, 0.5, 0.0, 0.7, 0.0, 0.6, 0.0],
            vein_opacity: vec![1.2, 0.8, 0.0, 1.0, 0.0, 0.5, 0.0],
            rare_veins: vec![VeinType::Crysrub, VeinType::Grat],
            rare_settings: vec![0.0, 0.7, 0.2, 0.6, 0.0, 1.0, 1.0, 0.84],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 24,
            name: "Desert 10",
            distribute: ThemeDistribute::Default,
            temperature: -4.0,
            planet_type: PlanetType::Ice,
            vein_spot: vec![9, 2, 2, 6, 2, 1, 0],
            vein_count: vec![0.8, 0.5, 0.8, 1.0, 0.7, 0.3, 0.0],
            vein_opacity: vec![0.8, 0.8, 1.2, 1.0, 1.0, 0.3, 0.0],
            rare_veins: vec![VeinType::Fireice, VeinType::Diamond, VeinType::Grat],
            rare_settings: vec![0.3, 1.0, 0.8, 1.0, 0.0, 1.0, 0.7, 1.0, 0.0, 0.4, 0.5, 0.7],
            gas_items: vec![],
            gas_speeds: vec![],
        },
        ThemeProto {
            id: 25,
            name: "Desert 11",
            distribute: ThemeDistribute::Interstellar,
            temperature: 0.0,
            planet_type: PlanetType::Ocean,
            vein_spot: vec![8, 3, 8, 1, 3, 9, 20],
            vein_count: vec![0.7, 0.6, 1.0, 1.0, 0.6, 1.0, 1.0],
            vein_opacity: vec![0.7, 0.5, 1.0, 1.0, 0.7, 1.2, 1.0],
            rare_veins: vec![VeinType::Fractal, VeinType::Crysrub, VeinType::Bamboo],
            rare_settings: vec![0.0, 0.5, 0.3, 1.0, 0.0, 1.0, 0.3, 1.0, 0.0, 0.5, 0.2, 1.0],
            gas_items: vec![],
            gas_speeds: vec![],
        },
    ]
});
