name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: v0.14.0

      - name: Install and Build
        shell: sh
        run: |
          npm install --omit=dev
          npm run build
          cp dist/index.html dist/404.html

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
